ACCESS_KEY = "alomari2025"

FOLDER_ID = "1D5gu4vO_YLjVHObfaRZc_XJEIPhlc_k4"
SHEET_ID = "1o_bx5KszHuU1ur-vYF7AdLH8ypvUmm7HXmxMOTzbhXg"

EMAIL_SENDER = "alrothematics.mohammad0@gmail.com"
EMAIL_PASSWORD = "rutesuutadzgdlbu"

TELEGRAM_BOT_TOKEN = "8111334709:AAHdMsnl1-_5SlEq7_AclZIVgQde0orzEuI"
TELEGRAM_CHAT_ID = "1991059938"

REDIRECT_URI = "https://advancedapp-version2.streamlit.app/"

GOOGLE_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "advanced-pdf-watermaker",
  "private_key_id": "02c5553d7be1d2cf6b51860b3142ed7fa08ef186",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2jyKlUth4iV7D\\nZOoVrtC1d7s+PkQbeyL0HU87YE2xOoJn+RDrcy0OcQXQEkwBkObhIjK3CmF2b/X9\\nP2NHkpyK2Iq9MvPNkuGL1czs9dYVljdv7xaGY6bPKK1NfdP7DPkKhfk1W43HcDaK\\nN9DWZsp6WlwDynE4ENRgEA+653PaGKfnf/QvF/GBTK/fsvS7WGGNY/UVbTjUWaZ+\\nPx2j6vIX2RmYPNDatI2DV9FRMI/Tepv65bMX5NhYbsUf+5vzi9HeyGa55fElO4U6\\nle7EQQCKpWIe9jHEWnRu8V1+M+tFCztWrfM6SX7wkheFutv80QjoWsi1GNZpscjR\\nWCueqMcFAgMBAAECggEAU9/DTS2Y4xhJ/3+3xKqCnT0bO+ejpvSWBI4Kvv7p8wks\\nrNRTn7lU9BOdVhFx9i46xSjPICWWzbF21RlwZYvIfEosw+xK8yIOmg5qjlwMNfLE\\nGZtBQBE8rGTF6ppq8CbvrJQNASTFKOI3TJ2ER10Gndwx9lPmXJnu2QvIDlkUcxil\\n9cMtTIQQTEFYjcBIsHK5L+k/7a6AH5z3JBkfeCzQRbuPw4AIzSa0qKKHsFuHR7/k\\nwZQ9cjh5BFaE6Eh/LsRcwUhfTy5mIbCuT9xgeAS3tg9xoO9JCMA/u61/vpGjA7QD\\nMkljMUQ2wRbu17LdcbBveskRca1mYIWcZQh3coIxKQKBgQDjVUspssD3l3ggobzm\\nVoc6PRdeNg/5lksP2tQLfmAnSNi2pN3YAbWCP0g59x4NIxfX3ioFdeDeDiiSw+bU\\nV2d+Lhhv4E2NOH8uCtYFsucm775fMFbFZrmwRxXkxz+LgBBako8zXF/70pbGN0zH\\n/HAT2h+GYueAds0tso/II7bAYwKBgQDNlHVHgQnSGoRGeKLMocP2GQgL2rOQB2mw\\n71t27+zV1vpasc3WcBV1EoRoevt5BQpSgsjZDtgHLCnbYDOHL9QJXglrP5KZAu+6\\nRB1ubeU4PpfXjQb2fdLBO0hjnJpoZXDltjj9146+Mi98x/IBQgzpdxwFKs20/JGM\\njx97CjoTdwKBgQCwfORIcBUtYrOJKeecLyr2xLzikDggvVRy76FVdvwxI3XTffUY\\noGMIxhZNohL7gfYdycV3zccQvY80OdB3o4+ePy0Llei/LVBXL2RusjCQYum5vq5u\\nvEyGlPljTmh/5aFMn6F670k5GImjQwVh8RIV5244B4rQierKgmjrqQZVHwKBgHH5\\ncqP36Gfxh5BCZY+px6jy68EWuSKK2Y/cxArGrblIfHg3x3Sxo1PKtlnuhOjtYHGq\\nTIv6bM5dL7+OMEMswxOGbRZmonHubNYJ2X9VshVirnA0ob2auHOk2FdRhVGHm/Xe\\n9u3UyjCsRiOZ/pOv+NSe0owS1QUYWeFhoARpARW1AoGBAKWJb3pEltPGAhukbvJx\\n6dyncQJ6AifqRTk24OumLDrbW34UK1zrLwgZ6oKJG12Qi4TCsq7s14VwWKXgYC3c\\nkZ0zb8Iu+QWKRoct+Bhy5FouMIuQXVCXS0Dh3uQuAh6kq0/4tSmvEC0acLJcbXFO\\nG4///E4C9psBZCJRytqYv58a\\n-----END PRIVATE KEY-----\\n",
  "client_email": "mohammad-397@advanced-pdf-watermaker.iam.gserviceaccount.com",
  "client_id": "112326269774768289900",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mohammad-397%40advanced-pdf-watermaker.iam.gserviceaccount.com"
}
"""
