ACCESS_KEY = "alomari2025"

FOLDER_ID = "1D5gu4vO_YLjVHObfaRZc_XJEIPhlc_k4"
SHEET_ID = "1o_bx5KszHuU1ur-vYF7AdLH8ypvUmm7HXmxMOTzbhXg"

EMAIL_SENDER = "alrothematics.mohammad0@gmail.com"
EMAIL_PASSWORD = "rutesuutadzgdlbu"

TELEGRAM_BOT_TOKEN = "8111334709:AAHdMsnl1-_5SlEq7_AclZIVgQde0orzEuI"
TELEGRAM_CHAT_ID = "1991059938"

GOOGLE_SERVICE_ACCOUNT = """
{
  "type": "service_account",
  "project_id": "charged-thought-465521-u9",
  "private_key_id": "b39c7d897b567db90b5786ba4b13efe98f7ed513",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9H2JvyAvKrcSg\\nY4NbuJe2RrwEN1bkwytGzQXuqQBgwC6KB9TnR4XcNsvtO4W20qlF0UGG9kh5ahO+\\nuGc6VaHUICu3UZsD/2YRjTVsRASEI4M3IKnSCK3HsEX4qL/CNcb3JPWgcnsNmYXR\\n0uhIhIc2BzubNCM9FEdwBuQuz6FkuTedQwaLulsrIEc915oXm6c0PJwW4NvDeJGG\\nFMBDQcOLC8DbNplBVi/ljVa6VErYGSBdYFuXtaogVmmAz8dLBDU2D5FNacW17Urn\\njUaOc4VD2OiHHuo2vidJmfXCGvWMcIuf32ZREq+Ng9fqLEemDEsp1KEXcf6lGfg7\\ncptMA+89AgMBAAECggEAJVQWAlk6Vplgx4WMzmRLcZtZjf18Ra/uEU3zX011OSOF\\nrBHqqHG6DqK0MpF+jXzcE18/r0taN7jDx++u1FlFlVB6QHc3gRz+gPVdt45fU9OM\\nmSt1yXKUFmeJEBECtGsX5/0gDDi8aA1G2AjodzPNWlEoJzStxecESKzbig/KW85J\\n+nH5vK5y44JVyHhq72cPtt/vMKUaqFMfKGiQDKOjpntQOz7zK+8qb2pMlOFfGnJl\\nuu1e/0MmHg2QZGnvc6BA3eaATGMSH7fzmylsw2dbD7+HV+F7Hv9Mgfelfm3Y1mxj\\nopqIwT/UZTxcRDf56L6/sVKw2+Lhl8aMjL7ojQiWwQKBgQDtcZXynR/gQ1qEniP0\\nB70+Ij3ZoKz6RMFbjqYyztNdoyJ9d3QMrzsmfYbHeBA75UtF/e6bEejJK/JunqIW\\nAQK446vf21QhmqmLH3A7maFcNaZ0OV7UCIuuuzHOJiWPLzuQz7EGGYrVOMWUWYCr\\nQzc89OqX/NlI8Nb54ktVPfuqYQKBgQDL5xA2+lhtjDACeMonACpD3Ywhu0udEhwa\\nZdQq7weXMRZXfuOe452yOkPuFNuD8Y6rGMfF35O3XGVbRgjsqMxZKTVANOUYQE+b\\nbJ8RXzFIumR2jT3iiZ72W/Uzzv3V0Z69L4xYDDetveKUVqZTBK+LOMuiPcJtto35\\nKs4NXbdKXQKBgQCJiNaLLnoNQ9ZFpPg8XNNAD0N2MHyhhnvdlbYtDeIeheTveeat\\nhj6j3+fW2HPGzd0ZEKpKBkipZhxJ+Pb3+ePixnWC+B82S8jS/gXbb/SoXacqASUt\\nejm2n1WNDEmLM5e0HKl0WA0zzmubr3A5Q3jWhSLxoJMXjfFn0q1CFeIVYQKBgGLo\\n+F2i/ShO268nRvC6TMZU/zgRsfFEqqtHgC8/elAmOK9C10npIkMlrnQcXAvaLpni\\n0G21MeO9h1FKXOPoUhBiQ/mcbxFfiP5dJ6B2q+KawEcd5sowdhMNsplqLIn/QGCH\\nYy4G5y95sCLDEbWtzTXc3DMcgGdWKfKXiBLFxjblAoGAdZHV5mJtDGJEFaz+cSZH\\nFAs6a5Z0bY2h5+z1RfUcLcFWCqYEPR+hvjfIJXgt9zJMH+Gs//Oo8T/bdaIcn23q\\nwFWYSJqyX8yawUoxZ5GBFzzTXWGJYEv0+rZC87ORHEjYrPREA8b6l/1SyTD15ghq\\nWdZ3Vw9iMny41GnHESsyovo=\\n-----END PRIVATE KEY-----\\n",
  "client_email": "alomari-pdf-tool@charged-thought-465521-u9.iam.gserviceaccount.com",
  "client_id": "100400088457955519681",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/alomari-pdf-tool%40charged-thought-465521-u9.iam.gserviceaccount.com"
}
"""
