ACCESS_KEY = "alomari2025"
FOLDER_ID = "1rXDiSvz2DA279LjUKufcw45_LqSGWdAz"
SHEET_ID = "1o_bx5KszHuU1ur-vYF7AdLH8ypvUmm7HXmxMOTzbhXg"
EMAIL_SENDER = "alrothematics.mohammad0@gmail.com"
EMAIL_PASSWORD = "rutesuutadzgdlbu"
TELEGRAM_BOT_TOKEN = "8111334709:AAHdMsnl1-_5SlEq7_AclZIVgQde0orzEuI"
TELEGRAM_CHAT_ID = "1991059938"

GOOGLE_SERVICE_ACCOUNT = """{
  "type": "service_account",
  "project_id": "advanced-pdf-watermaker",
  "private_key_id": "02c5553d7be1d2cf6b51860b3142ed7fa08ef186",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2jyKlUth4iV7D\nZOoVrtC1d7s+...\n-----END PRIVATE KEY-----\n",
  "client_email": "mohammad-397@advanced-pdf-watermaker.iam.gserviceaccount.com",
  "client_id": "112326269774768289900",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mohammad-397%40advanced-pdf-watermaker.iam.gserviceaccount.com"
}"""
